"""Create menu_item_ingredients table

Revision ID: 3763e723c8db
Revises: 9732b4c4f76b
Create Date: 2026-07-26 21:38:58.755869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3763e723c8db'
down_revision: Union[str, Sequence[str], None] = '9732b4c4f76b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity_used', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_item_id', 'inventory_item_id', name='uq_menu_item_inventory_item')
    )
    op.create_index(op.f('ix_menu_item_ingredients_inventory_item_id'), 'menu_item_ingredients', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_menu_item_ingredients_menu_item_id'), 'menu_item_ingredients', ['menu_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_item_ingredients_menu_item_id'), table_name='menu_item_ingredients')
    op.drop_index(op.f('ix_menu_item_ingredients_inventory_item_id'), table_name='menu_item_ingredients')
    op.drop_table('menu_item_ingredients')
    # ### end Alembic commands ###
