"""add_is_deleted_and_nullable_owner_to_restaurants

Revision ID: 4e6e820456b6
Revises: cd9af65bd67f
Create Date: 2026-07-30 15:26:11.642587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6e820456b6'
down_revision: Union[str, Sequence[str], None] = 'cd9af65bd67f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('restaurants', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('restaurants', 'is_deleted')
    # ### end Alembic commands ###
