"""add_payment_fields_to_orders

Revision ID: 7cd5b8bae7bf
Revises: ba93946d5804
Create Date: 2026-07-30 17:03:10.865979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd5b8bae7bf'
down_revision: Union[str, Sequence[str], None] = 'ba93946d5804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    payment_status_enum = sa.Enum('pending', 'paid', 'failed', name='payment_status_enum')
    payment_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('orders', sa.Column('payment_status', payment_status_enum, server_default='pending', nullable=False))
    op.add_column('orders', sa.Column('razorpay_order_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'razorpay_payment_id')
    op.drop_column('orders', 'razorpay_order_id')
    op.drop_column('orders', 'payment_status')

    payment_status_enum = sa.Enum('pending', 'paid', 'failed', name='payment_status_enum')
    payment_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
