"""add_party_size_to_reservations

Revision ID: ba93946d5804
Revises: b2e913882c47
Create Date: 2026-07-30 16:35:08.015889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba93946d5804'
down_revision: Union[str, Sequence[str], None] = 'b2e913882c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('party_size', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'party_size')
    # ### end Alembic commands ###
