"""add_total_tables_and_tables_model

Revision ID: e0f12808323e
Revises: 95851398e7bc
Create Date: 2026-07-30 13:42:51.287220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f12808323e'
down_revision: Union[str, Sequence[str], None] = '95851398e7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tables_restaurant_id'), 'tables', ['restaurant_id'], unique=False)
    op.add_column('restaurants', sa.Column('total_tables', sa.Integer(), nullable=False, server_default='10'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'total_tables')
    op.drop_index(op.f('ix_tables_restaurant_id'), table_name='tables')
    op.drop_table('tables')
    # ### end Alembic commands ###
